### ISSUE TITLE
Remove "Codeclimate"

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#211]
**Describe the bug**
There is a bug on pull requests (such as https://github.com/TimothyStiles/poly/pull/198) that cause CI to fail due to "codeclimate". It would appear that this "codeclimate" is an outdated and useless bit of code. It must have only survived due to our oversight, and so should be removed now as part of normal cleanup.

**To Reproduce**
1. Make code with more than 2 brain cells
2. PR that to Poly
3. Have "codeclimate" yell at you.

**Expected behavior**
Linters and tests should run as expected. The code can be reviewed by humans, like how God intended.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/2896607/134787175-32056cd8-c50e-47f8-97b1-6e96bfd4be9c.png)

**Additional context**
It would appear this bug is affecting other PRs as well, so this would appear to be a rather urgent.

**Comment by TimothyStiles** [comment]
Ahahahahahaha. Alright, alright I can tell that you're not happy but take a deep breath @Koeng101.

I actually like it because it often highlights stuff I do care about when reviewing pull requests. It's suggestions are dumb but the fact that it highlights complex code and repeats makes it easier for me to review what's going on.

I'll look into a way where it doesn't block merge but still generates that report to me. If it gives you the green check mark of happiness and prosperity but still highlights this stuff for me would that make you feel better @Koeng101?

**Comment by Koeng101** [comment]
yes. idc about the reports that much
