### ISSUE TITLE
Add poly version

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#25]
**Is your feature request related to a problem? Please describe.**
poly version should output the version of poly that is currently running. 

**Describe the solution you'd like**
```bash
$ poly version
0.0.1
```
**Describe alternatives you've considered**

**Additional context**

**Comment by TimothyStiles** [comment]
Here's a starting point : https://github.com/urfave/cli/blob/master/docs/v2/manual.md#version-flag

You'd want to check out how flags are defined in `main.go` and then try adding some of the stuff that's in the doc above.

Also, poly versions are tied to git tags. I'm not sure if `urfave/cli/v2` accounts for that but if it doesn't you'd probably have to write a github action that updates the version number based on tag before it's released with `.github/workflows/.release.yml`

**Comment by TimothyStiles** [comment]
Current thoughts on implementing this is to just have a `version.go` file that contains a variable that gets updated via github action on a tag push.

**Comment by TimothyStiles** [comment]
It turns out that `*cli.App` objects have specific fields for setting app version and toggling version printing off and on.

If you add these two lines after between [lines 43 and 44](https://github.com/TimothyStiles/poly/blob/7b0947a1970a5e9ecf556fb9745dcd2c826d5689/main.go#L43) of main.go it will print out the version.
```Go
	app.HideVersion = false
	app.Version = "0.2.0"
```

This is a pretty good first issue for getting familiar with github actions and improving our UI/UX. The tricky part would be updating the version when a tag is pushed. Might have to use an extra file like version.go to store version number.
