### ISSUE TITLE
Translate should have a setting to set first codon to M

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#305]
testTranslation, _ := codon.Translate(gfpDnaSequence, codon.GetCodonTable(11))

This fails in the case of  `gfpDnaSequence := "TTGGCT...TAA"`, which is perfectly valid for a start codon.

**Comment by carreter** [comment]
Should this be a toggleable setting, or just default behavior? Or maybe this is information that should live in the codon table?

From what I see according to [NCBI](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi):

>  The initiator codon - whether it is AUG, CTG, TTG or something else, - is by default translated as methionine (Met, M). The possible intiator codons are marked as 'M' in the second ('Starts') row of the translation tables.

However, it seems like [cryptic Leu-tRNA mediated initiation](https://pubmed.ncbi.nlm.nih.gov/22745432/) is also a thing that happens.

My proposal: modify the `Table` interface such that instead of returning a `[]string` of start codons, it returns a `map[string]rune` of start codons to the associated amino acid. We can have this be always map to `'M'` for our default codon tables, which means a user could make an implementation that corrects this behavior.

Working on this now.
