### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by rkrishnasanka** [TimothyStiles/poly#44]
**Is your feature request related to a problem? Please describe.**
Need for a python interface to use Poly with Python 3+. This will enable us to easily integrate parsers, etc. into other software pipelines. 

**Describe the solution you'd like**
A step by step guide on how to integrate poly into Python. This will allow inexperienced software developers to leverage poly's libraries and capabilities easily. From the structure of the codebase, it's hard to figure out what all features are available within the codebase. This should also include a set of easy to follow tutorials that can be used to instantiate the classes and use the API programmatically rather than running subprocesses.

**Describe alternatives you've considered**
I was looking up online how to do this and it seems like the general path is: Build a Shared Object -> Write CPython wrapper -> Use it. From my experience writing these wrappers is extremely annoying. I've used something like SWIG in the past to generate wrappers for C++ projects with python. I wonder if something similar exists for generating these wrappers. Alternatively, the wrappers need to be created as part of the projects development roadmap to provide API's

https://dev.to/astagi/extending-python-with-go-1deb

**Additional context**
I myself am new to the go ecosystem so I might be wrong about this. Would love to hear some feedback.

**Comment by TimothyStiles** [comment]
@rkrishnasanka I think supporting python 3 bindings is a little outside of `poly`'s current scope but if you're interested our docs are mostly up to date and go over parsers and hashing functions for both CLI and programmatic usage. 

https://timothystiles.github.io/poly/docs/

To be honest I haven't given much thought to supporting language bindings partially because I'd like for synbio as an industry to move away from Python for a whole lot of reasons. I think Python is a great language for prototyping and teaching but unlike Go it was never really meant for engineering stable and efficient industrial systems.

My concerns with providing bindings are the following:

* Issues with guaranteeing binding quality
* Vector for scope creep
* Admin and devops bloat

At this point I'd much prefer that users either use Go or the command line when using Poly but in the future there's really two options for porting `poly`'s functionality to other languages.

1. Bindings to each language
2. Provide a rest API

I think both solutions have merit and disadvantages. In either case I'd like to wait until `poly` hits a stable 1.0 and we have a real business case (i.e someone directly paying us for that feature) before taking up something like that.

If it's just the parsers and standardizing the poly JSON schema so other languages can use it @Koeng101 and I discussed that and it came down to a consensus that we should ship a JSON schema as a minor update sometime shorty after a 1.0 release as seen in pr #31.

**Comment by rkrishnasanka** [comment]
In that case, it would be good if you had:
1. A top-level API that reflects exactly the same interface as what is available with the command line - This would simplify maintenance and creation of language bindings. It would also mean that someone like me would be able to probably do a PR in case I want to use it for a project.
1. Support for pipes in case I want to shuttle inputs and outputs from the applications - this would simplify issues if we want to stream inputs and outputs from the application (I'm guessing this is already the case) 
1. JSON inputs/SBOL outputs and the corresponding RDF schemas as a part of the longer development roadmap. That would completely solve the need for running complicated command line gymnastics. 

I'm not the biggest fan of REST API's personally, too many layers of transformation in general.

**Comment by TimothyStiles** [comment]
The API and command line interface are pretty tightly woven and every command that's been shipped so far supports pipes and redirects with plenty of examples in the [documentation](https://timothystiles.github.io/poly/docs/cli-hashing#converting-a-sequence-to-json-and-hashing-a-sequence-from-a-stream).

JSON inputs and exports are already supported with our `AnnotatedSequence` struct and I'm happy to support SBOL3 when it becomes more clear what the schema will be. My current understanding is that no one has implemented a SBOL3 parser yet and its spec is still being finalized but maybe I'm wrong or things have changed.

If someone wants to write an SBOL2 parser I'd be up for reviewing/helping with that but at the moment I'm focusing on codon optimization which I want to get pushed out along with primer design and cloning.

**Comment by rkrishnasanka** [comment]
@TimothyStiles I was looking at the JSON interface and I think that would be best class that would be useful to build a python/c++ interface here. As we modify that we can keep adding whatever python functions we need to update the bindings.

Based on this article here: https://blog.filippo.io/building-python-modules-with-go-1-5/. It seems like it will be a fairly simple process of integrating the python interface from there.

**Comment by TimothyStiles** [comment]
@Koeng101 actually has a strategy for this when we start nearing 1.0 release. Essentially use json schema's to enforce standards between languages. The only reason I haven't merged his pull request is that I expect the sequence struct to be changed a couple more times in the next couple of months.
